### ISSUE TITLE
Problem with web-ifc node example

### ISSUE THREAD

**Issue by pablo-mayrgundter** [IFCjs/hello-world#25]
I tried updating and running this example.  First problem is it points to an old test IFC file, IFC/7/Tungasletta10_R01.ifc, which is no longer there.  I changed main.js to use the 01.ifc that is there but then get the following error:

```
pablo@top:~/ifcjs/hello-world/examples/web-ifc/ifc-to-json/node> node main.js
web-ifc: 0.0.34 threading: 0
TypeError: Cannot convert "undefined" to unsigned int
    at Object.toWireType (/Users/pablo/ifcjs/hello-world/node_modules/web-ifc/web-ifc-api-node.js:10184:21)
    at Object.GetLine (eval at new_ (/Users/pablo/ifcjs/hello-world/node_modules/web-ifc/web-ifc-api-node.js:9880:31), <anonymous>:8:26)
    at IfcAPI2.GetRawLineData (/Users/pablo/ifcjs/hello-world/node_modules/web-ifc/web-ifc-api-node.js:54841:28)
    at IfcAPI2.GetLine (/Users/pablo/ifcjs/hello-world/node_modules/web-ifc/web-ifc-api-node.js:54790:28)
    at saveProperties (/Users/pablo/ifcjs/hello-world/examples/web-ifc/ifc-to-json/node/main.js:42:26)
    at getAllItemsFromLines (/Users/pablo/ifcjs/hello-world/examples/web-ifc/ifc-to-json/node/main.js:33:13)
    at GetAllItems (/Users/pablo/ifcjs/hello-world/examples/web-ifc/ifc-to-json/node/main.js:26:5)
    at LoadFile (/Users/pablo/ifcjs/hello-world/examples/web-ifc/ifc-to-json/node/main.js:12:22)
```

Last commit to the repo:
```
> git log
commit 5d8f9fb7d613c13c912d288c9006b798bba7959a (HEAD -> main, origin/main, origin/HEAD)
Author: Antonio González Viegas <antoniogviegas@hotmail.com>
Date:   Wed Jun 22 00:39:02 2022 +0200

    Add psets to gltf import example
```

**Comment by agviegas** [comment]
Hey @pablo-mayrgundter I will try to update this when I have time. In the meantime, if you want to convert the properties to JSON, [here](https://github.com/IFCjs/web-ifc-viewer/blob/6f4a97b1cdca2c2eb440ba8c704a0cc70c107678/viewer/src/components/ifc/ifc-properties.ts#L31) you can find an example of how to do that. Cheers!

**Comment by nithin-cuezap** [comment]
Hi @agviegas, I just ran into this same issue. The error was being thrown for the last index in the loop at `line.get(index)`

https://github.com/IFCjs/hello-world/blob/0d7b804fbf83773e59be0e3ffd7300767a8dceb2/examples/web-ifc/ifc-to-json/node/main.js#L41

Did some quick tests and it seems like the current for loop is starting at 2nd line and going past the last line. setting the loop index to run from 0 to (size-1) seems to fix the issue.

https://github.com/IFCjs/hello-world/blob/0d7b804fbf83773e59be0e3ffd7300767a8dceb2/examples/web-ifc/ifc-to-json/node/main.js#L31 

I can raise a PR if you haven't started looking int

**Comment by agviegas** [comment]
Hey @nithin-cuezap if you could create a pull request, it would be great! We are building the contribution documentation right now (the plan is to publish everything before the end of this year), but feel free to just edit this example and create the PR. 

I've made this issue a [bounty](https://bounties.ifcjs.io/) (you can check it out [here](https://airtable.com/embed/shrD7oOspTUpElFX9/tblKwrKdBmdTG2L3I/viwu2a2cJLvEFTvA6/recqeZvZUG66B6QZ9?backgroundColor=orange&viewControls=on)), so if you make this, you can get some money for your time. 🙂 You can use the ::take command to take it. Cheers!

**Comment by agviegas** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @agviegas! Thanks for taking this bounty! The due date is November 22, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by agviegas** [comment]
::drop

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::drop

Hi, @agviegas! Thanks for giving it a try! It’s now once again available for anyone to take.

**Comment by nithin-cuezap** [comment]
thanks @agviegas! I'll pick this up.

**Comment by nithin-cuezap** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @nithin-cuezap! Thanks for taking this bounty! The due date is November 24, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by nithin-cuezap** [comment]
hi @agviegas, Created PR #46 for this issue.

Another unrelated observation - Noticed this node example folder is not a node project (it doesn't have package.json).
Is that intentional?  To work on the fix, I converted this to a node project with `npm init` and added web-ifc as a dependency. 
I did not commit those changes as they were unrelated to this issue per se. 

But I feel it might be easier for someone trying out the examples, to have that node example as an independent project in itself. If you'd like me to commit the package.json in this same PR, please let me know.

**Comment by nithin-cuezap** [comment]
::done

**Comment by agviegas** [comment]
Great, we'll review this asap :) Thanks a lot!

**Comment by agviegas** [comment]
### 🔴🔴🔴

Hi, @nithin-cuezap! The date is past due, your assignment has been revoked. It’s now available for anyone to take.

**Comment by agviegas** [comment]
::done

**Comment by makc** [comment]
@agviegas this one is now 1st available bounty at [airtable](https://airtable.com/embed/shrD7oOspTUpElFX9/tblKwrKdBmdTG2L3I?backgroundColor=orange&viewControls=on)🥲

**Comment by aka-blackboots** [comment]
Hey @makc, I updated the Airtable to reflect all the recent changes. However, if I have missed something don't hesitate to let me know. 
Thank you for helping out🚀
