### ISSUE TITLE
Nice Ambient Occlusion

### ISSUE THREAD

**Issue by agviegas** [IFCjs/hello-world#4]
## 📋 GENERAL: 

- Bounties page: https://bounties.ifcjs.io/
- Required skills: `Three.js`.
- Bounty: $2000.

________________________________________________________________________

## ⚔ CHALLENGE:

Autodesk Forge has a very nice ambient occlusion that gives it a cool look. You can check it out here: 

- https://forge.autodesk.com/sites/default/files/2019-10/screen_shot_2019-09-06_at_10.21.54_am_2.png

As far as we know, Forge is built Three.js (around version 70), so we are convinced that it is possible to achieve that effect, especially considering all the advances Three.js has made since then. 

________________________________________________________________________

## 👩‍⚖️ REQUIREMENTS: 

- Similar look to Forge viewer.

- Decent performance (don't go below 30 fps with medium-size IFC models in a laptop). 

________________________________________________________________________

## 🔥 STARTING MATERIAL: 

You can use the hello world repository, which has a simple example of IFC.js that you can use as starting point:

- https://github.com/IFCjs/hello-world

- https://github.com/IFCjs/hello-world/tree/main/examples/web-ifc-three/introduction

Here you have some IFC files to test:

- https://github.com/IFCjs/test-ifc-files

In addition to that, there are multiple types of ambient occlusion examples published in official Three.js resources:

- https://threejs.org/examples/webgl_postprocessing_sao.html

- https://threejs.org/examples/webgl_postprocessing_ssao.html

**Comment by DanielSBoba** [comment]
Hi @agviegas ! 
I would like to give it a try. 👩‍🎨
Is the deadline of 25.05 fine?

Cheers!

**Comment by ManuelRomer** [comment]
Also working on it since 16/05 10a.m. CET, sorry.

**Comment by ManuelRomer** [comment]
Hey Daniel, we relatively achieved it but don't worry, this is about to improve and contributing, so if you have some stuck or needings, feel free to contact with me at discord-ifc (look for someone there called ManeRom). If you want, I can share it there with you and reach to the best possible solution.  Let's go for a good and productive day.

![ShareX_q80W8kyoWQ](https://user-images.githubusercontent.com/74239475/168758909-a26832e5-1e8a-4dea-8c6a-293f7a75aceb.png)

**Comment by DanielSBoba** [comment]
Well... so we both worked on it. 
![image](https://user-images.githubusercontent.com/62248969/168773100-746133e4-caa1-4628-b947-0d0a646b8b56.png)

**Comment by ManuelRomer** [comment]
As you noticed in here previously than me, of course feel as the owner of this issue, and take me on count as I told you, but as I'm looking right now, you did it great.

**Comment by agviegas** [comment]
Hey @DanielSBoba no worries, you commented first, so it's yours. 
It's very nice that @ManuelRomer wants to share his implementation 😄
Looking forward to see how this turns out!!

**Comment by DanielSBoba** [comment]
Hi @ManuelRomer, thank you! Unfortunately, I couldn't find anyone with the "ManeRom" nickname on the IFC.js discord channel. 

Could you please shot me a message there? My nick is "DBo".

**Comment by ManuelRomer** [comment]
Hi, good morning. I spoke to you directly at Discord, feel free to ask us there

**Comment by MahmoudAbdelRahman** [comment]
Amazing job guys. This feature is so important

**Comment by DanielSBoba** [comment]
Hi guys, I was able to manage this: #12
Please let me know what can be improved and feel free to contribute.😁
