### ISSUE TITLE
Nice Edges

### ISSUE THREAD

**Issue by agviegas** [IFCjs/hello-world#5]
## 📋 GENERAL: 

- Bounties page: https://bounties.ifcjs.io/
- Required skills: `Three.js`.
- Bounty: $2000.

________________________________________________________________________

## ⚔ CHALLENGE:

Autodesk Forge has a very nice edges that gives it a cool look. You can check it out here: 

- https://forge.autodesk.com/sites/default/files/2019-10/screen_shot_2019-09-06_at_10.21.54_am_2.png

As far as we know, Forge is built Three.js (around version 70), so we are convinced that it is possible to achieve that effect, especially considering all the advances Three.js has made since then. 

We have tried THREE.EdgesGeometry (https://threejs.org/docs/#api/en/geometries/EdgesGeometry), but it's not very performant in bigger models. A postproduction or shader approach is what we are looking for.

________________________________________________________________________

## 👩‍⚖️ REQUIREMENTS: 

- Similar look to Forge viewer.

- Decent performance (don't go below 30 fps with medium-size IFC models in a laptop). 

________________________________________________________________________

## 🔥 STARTING MATERIAL: 

You can use the hello world repository, which has a simple example of IFC.js that you can use as starting point:

- https://github.com/IFCjs/hello-world

- https://github.com/IFCjs/hello-world/tree/main/examples/web-ifc-three/introduction

Here you have some IFC files to test:

- https://github.com/IFCjs/test-ifc-files

In addition to that, there are multiple related discussions in the three.js forum. For instance:

- https://discourse.threejs.org/t/ldraw-like-edges/17100

**Comment by Jsanchez4** [comment]
Hi Antonio, I'll take care of this one!

**Comment by Jsanchez4** [comment]
It will be ready for 27.05

**Comment by agviegas** [comment]
Fantastic @Jsanchez4 😊
