### ISSUE TITLE
hello-world tutorial for ifc-web returning empty array

### ISSUE THREAD

**Issue by nicolasbolcatto** [IFCjs/hello-world#52]
Hello-world tutorial for ifc-web is returning [ ] (array named spaces) for every .ifc file available for the same tutorial. I've checked and 
let lines = ifcapi.GetLineIDsWithType(modelID, IFSPACE);
returns an empty array.

Is it possible to check what might be the problem? I'm copying the repo url:

https://github.com/nicolasbolcatto/web-ifc-hello-world

**Comment by agviegas** [comment]
Might it be that those IFCs don't have spaces defined? Alternatively, when configuring web-ifc, you can decide whether you want it to load the spaces or not by setting its [configuration](https://ifcjs.github.io/info/docs/Guide/web-ifc-three/api/#applywebifcconfig). This has to be configured before loading the IFC file.
