### ISSUE TITLE
HBJSON exporter

### ISSUE THREAD

**Issue by agviegas** [IFCjs/hello-world#6]
## 📋 GENERAL: 

- Bounties page: https://bounties.ifcjs.io/
- Required skills: `Three.js`.
- Bounty: $1000.

________________________________________________________________________

## ⚔ CHALLENGE:

One of the most powerful use cases for BIM is building energy analysis. Luckily, there are brilliant people who are already implementing this problem; we are referring to the people at Ladybug Tools.

- https://www.ladybug.tools/

One of their free libraries for energy analysis is Honeybee, which uses their own open HBJSON format. The goal of this task is to extract all the necessary data from an IFC and create an HBJSON file that HoneyBee can read correctly.

We are aware that many IFCs do not have the necessary information for their energy analysis, and the aim of this task is not to generate that information. We are going to provide an IFC that does have that data, so you can concentrate on simply extracting it to generate the JSON. 

Quoting Mostapha Sadeghipour (Ladybug tools):
The way a simulation model should be prepared depends on the type of the simulation. A model can be built face-by-face or it can be built room-by-room. The first one is great for daylight simulation. The second one is what is needed for energy simulation. In the IFC world IFCSpaces are supposed to those rooms that should be used for energy simulation but it is not as easy. Here you have a related discussion in OSArch:

- https://community.osarch.org/discussion/109/energy-modeling

Regarding HBJSON, and quoting Mostapha again: The schema is open source and documented here: https://www.ladybug.tools/honeybee-schema/model.html#tag/model_model - Model is the object that describes the whole building.: You can think about it as a mini-IFC fo

We use OpenAPI toolkit to generate different SDKs. We use Python and C# actively. We have never used the JS one but this project might be the right place to use it. Once we generate a valid HBJSON file the rest of the process is taken care of with our translators. Most of our translators are written in Python but since we use the HBJSON file in the middle as the transition layer it doesn't really matter what language you want to use to generate the HBJSON file.

________________________________________________________________________

## 👩‍⚖️ REQUIREMENTS: 

- Generate a file that HoneyBee can read.

________________________________________________________________________

## 🔥 STARTING MATERIAL: 

You can use the hello world repository, which has a simple example of IFC.js that you can use as starting point:

- https://github.com/IFCjs/hello-world

- https://github.com/IFCjs/hello-world/tree/main/examples/web-ifc-three/introduction

Here you have an IFC files with the necesary information to make energy analysis:

- https://drive.google.com/file/d/1vvCvFgdtNEyT3HBeuVwL-cgZsvTDZn-Z/view?usp=sharing

Here you have the HBJSON specification:

- https://www.ladybug.tools/honeybee-schema/model.html#tag/model_model

Finally, here you have some HBJSON examples:

- https://drive.google.com/drive/folders/1cGLIfQRNN0avz_v7Ya1nf5rMC_wKoKEx?usp=sharing

**Comment by MattiaBressanelli** [comment]
Hi, how much time would be available to complete the task?

**Comment by denim2x** [comment]
I'll take on this assignment, if that's allright

**Comment by agonzalezesteve** [comment]
@denim2x Here you have a sverchok node in python that reads an IFC using ifcopenshell and writes an HBJSON https://github.com/agonzalezesteve/BIM2BEM/blob/main/nodes/IFCExportToHBSJON.py

**Comment by MarkusSteinbrecher** [comment]
Great idea for a bounty. Cannot wait to see the result. Happy to provide some test models if that helps.

**Comment by agviegas** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @agviegas! Thanks for taking this bounty! The due date is September 17, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by agviegas** [comment]
::drop

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::drop

Hi, @agviegas! Thanks for giving it a try! It’s now once again available for anyone to take.

**Comment by rrdls** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @rrdls! Thanks for taking this bounty! The due date is October 26, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by agviegas** [comment]
### 🔴🔴🔴

Hi, @rrdls! The date is past due, your assignment has been revoked. It’s now available for anyone to take.

**Comment by rrdls** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @rrdls! Thanks for taking this bounty! The due date is November 17, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by rrdls** [comment]
::extend

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::extend

Hi, @rrdls! The due date is successfully extended by 21 days to December 8, 2022 UTC.

**Comment by agviegas** [comment]
### 🔴🔴🔴

Hi, @rrdls! The date is past due, your assignment has been revoked. It’s now available for anyone to take.

**Comment by rrdls** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @rrdls! Thanks for taking this bounty! The due date is December 30, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by rrdls** [comment]
::drop

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::drop

Hi, @rrdls! Thanks for giving it a try! It’s now once again available for anyone to take.

**Comment by johltn** [comment]
I'd like to take on this bounty please

**Comment by agviegas** [comment]
Hey @johltn you can take it using the ::take command, like you see in the comments above.

**Comment by johltn** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @johltn! Thanks for taking this bounty! The due date is January 23, 2023 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by johltn** [comment]
::extend

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::extend

Hi, @johltn! The due date is successfully extended by 21 days to February 13, 2023 UTC.

**Comment by johltn** [comment]
::drop

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::drop

Hi, @johltn! Thanks for giving it a try! It’s now once again available for anyone to take.

**Comment by johltn** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @johltn! Thanks for taking this bounty! The due date is March 5, 2023 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by johltn** [comment]
Hello, here is a tentative https://github.com/IFCjs/hello-world/pull/50 for the HBJSON exporter :blush:

**Comment by agviegas** [comment]
### 🔴🔴🔴

Hi, @johltn! The date is past due, your assignment has been revoked. It’s now available for anyone to take.

**Comment by ENG-Mazri** [comment]
Hello! if @johltn is not willing to take this again, I'd like to take on; I've recently done a serverside app to convert IFC to .glb (costomized) and I'd like to do this task, I might need some help later on from the @chriswmackey and the Pollination guys to check with me the results as I've never profissionally worked with energy or weather analysis, I've already tryed ladybug and honeybee in grasshopper and I'm reading the documentation though.

**Comment by agviegas** [comment]
Hey @ENG-Mazri @johltn submitted the PR before the deadline, so now we are going to review that :) but don't worry, we'll make more bounties covering this topic!

**Comment by johltn** [comment]
::extend

**Comment by johltn** [comment]
::expense::132232

**Comment by agviegas** [comment]
### 🎉🎉🎉

Hi, @https://github.com/johltn! Thanks for your contributions! The reward of this bounty has been transferred to your Open Collective account.
