### ISSUE TITLE
Simple clash detector

### ISSUE THREAD

**Issue by agviegas** [IFCjs/hello-world#7]
## 📋 GENERAL: 

- Bounties page: https://bounties.ifcjs.io/
- Required skills: `Three.js`.
- Bounty: $1000.

________________________________________________________________________

## ⚔ CHALLENGE:

A very interesting use case for BIM is collision detection. There are many companies that sell solutions whose only purpose is this.

IFC.js is already able to create a simple example where it detects collision between objects of the user's choice using subsets. This should be easy thanks to Garrett Johnson's work with three-mesh-bvh:

- https://github.com/gkjohnson/three-mesh-bvh

________________________________________________________________________

## 👩‍⚖️ REQUIREMENTS: 

- Create a simple clash detector that detects whether two subsets are colliding or not.

- Get the IDs of the items that collide.

- Filter clashes by intersection distance.

________________________________________________________________________

## 🔥 STARTING MATERIAL: 

You can use the hello world repository, which has a simple example of IFC.js that you can use as starting point:

- https://github.com/IFCjs/hello-world

- https://github.com/IFCjs/hello-world/tree/main/examples/web-ifc-three/introduction

Here you have some IFC files to test:

- https://github.com/IFCjs/test-ifc-files

Here you have some examples Garrett Johnson regarding collision in his three-mesh-bvh repository:

- https://gkjohnson.github.io/three-mesh-bvh/example/bundle/shapecast.html

- https://gkjohnson.github.io/three-mesh-bvh/example/bundle/edgeIntersect.html

In addition to that, here you have the IFC.js subset tutorial to understand how they work:

- https://ifcjs.github.io/info/docs/Guide/web-ifc-three/Tutorials/Highlighting

**Comment by aka-blackboots** [comment]
I will take up this bounty challenge, I have completed **Requirement Number 1** (Attaching Image in the comments, I will also build a basic interface). 

For other requirements of this same bounty, my time estimate is before this week.

**When the clash is not happening (Two windows)**
![Screenshot (380)_LI](https://user-images.githubusercontent.com/47943405/168880492-d7fcd4e8-07a6-44fd-85b6-503ab8f29c44.jpg)


**When the clash is happening - Roof(22620) and Side Wall(186)**
![Screenshot (382)_LI](https://user-images.githubusercontent.com/47943405/168880965-1c820850-f522-4f9c-937a-c2c9d168484f.jpg)

**Comment by agviegas** [comment]
Looking great @aka-blackboots ! 🚀
